apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
  namespace: iicpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard-service
  template:
    metadata:
      labels:
        app: leaderboard-service
    spec:
      containers:
      - name: leaderboard-service
        image: leaderboard-service:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"