apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-fleet-hpa
  namespace: iicpc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-fleet
  minReplicas: 2
  maxReplicas: 10          # scales up to 10 pods = 1000 bots
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70