apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
  namespace: iicpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
      - name: submission-service
        image: submission-service:latest
        imagePullPolicy: Never       # use local image in minikube
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: submission-config
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"