apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
        resources:
          limits:
            cpu: {{ .Values.redis.resources.limits.cpu }}
            memory: {{ .Values.redis.resources.limits.memory }}
          requests:
            cpu: {{ .Values.redis.resources.requests.cpu }}
            memory: {{ .Values.redis.resources.requests.memory }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: redis
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  clusterIP: None